### ISSUE TITLE
紧急处理

### ISSUE THREAD

**Issue by JKsn916** [railmapgen/railmapgen.github.io#18]
TypeError: Failed to fetch dynamically imported module: https://railmapgen.github.io/assets/app-root-7ff8f98b.js

    at Lazy
    at Suspense
    at t (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:370:113225)
    at pC (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:323:15960)
    at _w (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:1:10083)
    at FI (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:1:70532)
    at D4 (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:15:23183)
    at tY (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:370:54062)
    at https://railmapgen.github.io/assets/vendor-5a68c8dd.js:370:54443
    at kQ (https://railmapgen.github.io/assets/vendor-5a68c8dd.js:370:59687)

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。方便描述一下您是在什么样的操作下遇到这个问题的呢？已经你的浏览器和操作系统版本是多少呢？因为首页这两周都没有任何更新所以想确认一下问题来源。
